// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example/example.proto

package example

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Person struct {
	Id                   uint64           `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string           `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string           `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Home                 *Person_Location `protobuf:"bytes,4,opt,name=home,proto3" json:"home,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c78cffa5d645ba4, []int{0}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Person) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetHome() *Person_Location {
	if m != nil {
		return m.Home
	}
	return nil
}

type Person_Location struct {
	Lat                  float64  `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng                  float64  `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person_Location) Reset()         { *m = Person_Location{} }
func (m *Person_Location) String() string { return proto.CompactTextString(m) }
func (*Person_Location) ProtoMessage()    {}
func (*Person_Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c78cffa5d645ba4, []int{0, 0}
}

func (m *Person_Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person_Location.Unmarshal(m, b)
}
func (m *Person_Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person_Location.Marshal(b, m, deterministic)
}
func (m *Person_Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person_Location.Merge(m, src)
}
func (m *Person_Location) XXX_Size() int {
	return xxx_messageInfo_Person_Location.Size(m)
}
func (m *Person_Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Person_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Person_Location proto.InternalMessageInfo

func (m *Person_Location) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *Person_Location) GetLng() float64 {
	if m != nil {
		return m.Lng
	}
	return 0
}

func init() {
	proto.RegisterType((*Person)(nil), "example.Person")
	proto.RegisterType((*Person_Location)(nil), "example.Person.Location")
}

func init() { proto.RegisterFile("example/example.proto", fileDescriptor_1c78cffa5d645ba4) }

var fileDescriptor_1c78cffa5d645ba4 = []byte{
	// 271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4d, 0xad, 0x48, 0xcc,
	0x2d, 0xc8, 0x49, 0xd5, 0x87, 0xd2, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xec, 0x50, 0xae,
	0x94, 0x78, 0x59, 0x62, 0x4e, 0x66, 0x4a, 0x62, 0x49, 0xaa, 0x3e, 0x8c, 0x01, 0x51, 0xa1, 0xb4,
	0x94, 0x89, 0x8b, 0x2d, 0x20, 0xb5, 0xa8, 0x38, 0x3f, 0x4f, 0x48, 0x8a, 0x8b, 0x29, 0x33, 0x45,
	0x82, 0x51, 0x81, 0x51, 0x83, 0xc5, 0x89, 0x6b, 0xd7, 0xcb, 0x03, 0xcc, 0xac, 0x46, 0xcc, 0x0a,
	0xcf, 0xd9, 0x83, 0x98, 0x32, 0x53, 0x84, 0xe4, 0xb9, 0x58, 0x53, 0x73, 0x13, 0x33, 0x73, 0x24,
	0x98, 0x14, 0x18, 0x35, 0x38, 0x9d, 0x38, 0x41, 0xd2, 0x2c, 0x45, 0x4c, 0x09, 0x8c, 0x41, 0x10,
	0x71, 0x21, 0x3b, 0x2e, 0x96, 0xbc, 0xc4, 0xdc, 0x54, 0x09, 0x66, 0xb0, 0xbc, 0x16, 0x48, 0x5e,
	0xb5, 0x48, 0x59, 0xa3, 0x81, 0xc9, 0x48, 0x2e, 0x2e, 0xda, 0x40, 0xd7, 0xd2, 0x51, 0x37, 0x2a,
	0x51, 0xb7, 0x2a, 0x56, 0x5b, 0x43, 0x01, 0x99, 0xa7, 0xa9, 0xa5, 0x12, 0x04, 0xd6, 0x27, 0x64,
	0xc1, 0xc5, 0x92, 0x91, 0x9f, 0x9b, 0x2a, 0xc1, 0xa2, 0xc0, 0xa8, 0xc1, 0x6d, 0x24, 0xa1, 0x07,
	0xf3, 0x07, 0xc4, 0x6d, 0x7a, 0x3e, 0xf9, 0xc9, 0x89, 0x25, 0x99, 0xf9, 0x79, 0x50, 0x87, 0x75,
	0x31, 0x32, 0x09, 0x30, 0x06, 0x81, 0x75, 0x48, 0xa5, 0x70, 0x71, 0xc0, 0x64, 0x85, 0xb4, 0xb9,
	0x98, 0x73, 0x12, 0x4b, 0xc0, 0x7e, 0x60, 0x74, 0x92, 0x04, 0x29, 0x15, 0x11, 0x12, 0x92, 0x64,
	0x00, 0x81, 0x86, 0x30, 0x07, 0x4d, 0x28, 0xe3, 0x40, 0x10, 0x48, 0x15, 0x58, 0x71, 0x5e, 0x3a,
	0xd8, 0x47, 0x18, 0x8a, 0xd3, 0x60, 0x8a, 0xd3, 0x40, 0x8a, 0xf3, 0xd2, 0x93, 0xd8, 0xc0, 0xc1,
	0x65, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x14, 0x97, 0xea, 0xf4, 0x69, 0x01, 0x00, 0x00,
}
